site_name: Documentazione
site_url: https://mydomain.org/mysite
theme:
  name: material

  logo: AssetSito/butterfly.png

  palette:
  

    # Palette toggle for light mode
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-1
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant.preview
    - navigation.top
    - navigation.sections
    - navigation.expand


nav:
  - Io: Me.md
  - About:
    - Chi sono: About/Chisono.md
    - Errori: About/Errori.md



