site_name: Documentazione
site_url: https://mydomain.org/mysite
theme:
  name: material

  font:
    text: Delius

  language: it

  logo: AssetSito/butterfly.png

  palette:
  

    # Palette toggle for light mode
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-1
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant.preview
    - navigation.top
    - navigation.sections
    - navigation.expand

  plugins:
     - search
     - mkdocs-video
  


nav:
  - Me: Me.md
  - About:
    - Errori: About/Errori.md
    - Lavori: Lavori/Lavori.md
  - Lab: Lab/Manifesta.md
  
